version: '3.8'
services:
  s3mer:
    container_name: s3mer
    restart: always
    image: ghcr.io/theasda/s3mer:${IMAGE_VERSION}
    ports:
      - 9000:9000
    volumes:
      - /docker/cert.crt:/app/cert.crt
      - /docker/ca.crt:/app/ca.crt
      - /docker/private.key:/app/private.key
    labels: 
      - traefik.enable=true
      - traefik.http.routers.s3mer.rule=Host(`okinazuno.me`)
      - traefik.http.routers.s3mer.entrypoints=https

      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.s3mer-redirs.rule=hostregexp(`{host:.+}`)
      - traefik.http.routers.s3mer-redirs.entrypoints=http
      - traefik.http.routers.s3mer-redirs.middlewares=redirect-to-https

networks:
  default:
    external: true
    name: traefik-network
