version: '3.8'
services:
  s3mer:
    container_name: s3mer
    restart: always
    image: ghcr.io/theasda/s3mer:${IMAGE_VERSION}
    ports:
      - 9000:9000
    labels: 
      - traefik.http.routers.s3mer.rule=Host(`okinazuno.me`)
      - traefik.http.routers.s3mer.tls=true
      - traefik.http.routers.s3mer.tls.certresolver=letsEncrypt

networks:
  default:
    external: true
    name: traefik-network
